// <auto-generated />
using System;
using Bothniabladet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bothniabladet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200413221004_migration1")]
    partial class migration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bothniabladet.Data.EditedImage", b =>
                {
                    b.Property<int>("EditedImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ImageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.HasKey("EditedImageId");

                    b.HasIndex("ImageId");

                    b.ToTable("EditedImage");
                });

            modelBuilder.Entity("Bothniabladet.Data.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ImageLicenseId")
                        .HasColumnType("int");

                    b.Property<int>("ImageMetaDataId")
                        .HasColumnType("int");

                    b.Property<int>("basePrice")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("issue")
                        .HasColumnType("datetime2");

                    b.Property<int>("sectionPublished")
                        .HasColumnType("int");

                    b.HasKey("ImageId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Bothniabladet.Data.EditedImage", b =>
                {
                    b.HasOne("Bothniabladet.Data.Image", null)
                        .WithMany("EditedImages")
                        .HasForeignKey("ImageId");
                });
#pragma warning restore 612, 618
        }
    }
}
